excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://arthurbarros.github.io
title: Arthur Barros
email: arthbarros [at] gmail [dot] com
tagline: Obvious conclusions
description: coding around
twitter: arthbarros
github_user: arthurbarros
medium_user: arthbarros
linkedin: https://www.linkedin.com/in/arthurbarros
livecoding: https://www.livecoding.tv/arthurbarros/
paginate: 5
