excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://arthurbarros.github.io
title: Arthur Barros
email: arthbarros [at] gmail [dot] com
tagline: Obvious conclusions
description: coding around
twitter: arthbarros
github_user: arthurbarros
linkedin: https://www.linkedin.com/in/arthurbarros
referral_digitaocean: https://www.digitalocean.com/?refcode=cc1252c71235
paginate: 5
