# Site settings
title: Arthur's Neural Network
header-img: img/home-bg.jpg
email: arthbarros [at] gmail [dot] com
copyright_name: Arthur Barros
description: "Artificial Intelligence and Software Engineering"
baseurl: "/"
url: "http://arthurbarros.github.io"
twitter_username: arthbarros
github_username:  arthurbarros
linkedin_username: arthurbarros

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-69349112-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
