excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://arthurbarros.github.io
title: Arthur Barros
email: arthbarros [at] gmail [dot] com
tagline: Obvious conclusions
description: Geeking around
twitter: arthbarros
github_user: arthurbarros
linkedin: https://www.linkedin.com/in/arthurbarros
paginate: 5
