excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://arthurbarros.github.io
title: Arthur Barros
email: arthbarros [at] gmail [dot] com
twitter: arthbarros
github_user: arthurbarros
linkedin: https://www.linkedin.com/in/arthurbarros
paginate: 5
highlighter: rouge
